import = [
    "~/.config/alacritty/themes/themes/noctis-lux.toml"
]

live_config_reload = true

[env]

    TERM = "xterm-256color"


[window]

    padding.x = 10
    padding.y = 10

    decorations = "Buttonless"
    
    opacity = 0.8
    blur = true
    
    option_as_alt = "Both"

[keyboard]

    bindings = [
        { key = "V", mods = "Command|Control", action = "ToggleViMode" },
    ]
