import = [
    "~/.config/alacritty/themes/themes/alabaster.toml"
]

[env]

    TERM = "xterm-256color"


[window]

    padding.x = 10
    padding.y = 10

    decorations = "Buttonless"
    
    opacity = 0.8
    blur = true
