import = [
    "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

live_config_reload = true

[env]

    TERM = "xterm-256color"


[window]

    padding.x = 10
    padding.y = 10

    decorations = "Buttonless"
    
    opacity = 0.9
    blur = true
    
    option_as_alt = 'OnlyLeft'

